export const REQUEST_VISITS = 'vet/REQUEST_VISITS'
export const RECEIVE_VISITS = 'vet/RECEIVE_VISITS'
export const ACTIVATE_FILTER = 'vet/ACTIVATE_FILTER'

export const REQUEST_APPOINTMENTS = 'vet/REQUEST_APPOINTMENTS'
export const RECEIVE_APPOINTMENTS = 'vet/RECEIVE_APPOINTMENTS'

export const SAVE_THE_DATE_BEGIN = 'vet/SAVE_THE_DATE_BEGIN'
export const SAVE_THE_DATE_END = 'vet/SAVE_THE_DATE_END'

export const DELETE_THE_DATE_BEGIN = 'vet/DELETE_THE_DATE_BEGIN'
export const DELETE_THE_DATE_END = 'vet/DELETE_THE_DATE_END'
