export const REQUEST_VETS = 'vets/REQUEST_VETS'
export const RECEIVE_VETS = 'vets/RECEIVE_VETS'
export const CHANGE_VIEW_TO_THUMBNAIL = 'vets/CHANGE_VIEW_TO_THUMBNAIL'
export const CHANGE_VIEW_TO_LIST = 'vets/CHANGE_VIEW_TO_LIST'