export const REQUEST_VETS = 'vets/REQUEST_VETS'
export const RECEIVE_VETS = 'vets/RECEIVE_VETS'
export const CHANGE_VIEW_TO_THUMBNAIL = 'vets/CHANGE_VIEW_TO_THUMBNAIL'
export const CHANGE_VIEW_TO_LIST = 'vets/CHANGE_VIEW_TO_LIST'
export const CHANGE_VIEW_TO_FAVOURITE = 'vets/CHANGE_VIEW_TO_FAVOURITE'
export const FILTER_VETS_BY_NAME = 'vets/FILTER_VETS_BY_NAME'

export const IS_VET_IN_FAVOURITE = 'vet/IS_VET_IN_FAVOURITE'